### ISSUE TITLE
Support for TCutG Objects in Histograms

### ISSUE THREAD

**Issue by okawak** [CRIB-project/artemis_crib#6]
# Current Status

In previous experiments, we created TCutG objects using custom commands and configured the system to load them automatically. These objects were then referenced in the histogram definition file to perform event selection.

# Issue

When multiple histograms reference the same TCutG object, the cut is only applied to the first histogram. Subsequent histograms fail to apply the cut properly.

- Example: TCutG object named `tel1`:

```yaml
group:  
  - name: hist_group  
    title: hist_group  
    contents:  
      - name: NAME1  
        title: TITLE1  
        x: *xaxis1  
        y: *yaxis1  
        cut: tel1  
      - name: NAME2  
        title: TITLE2  
        x: *xaxis2  
        y: *yaxis2  
        cut: tel1  # not applied?
```

# Possible Cause

The histogram definition file might not be designed to handle TCutG objects properly, and we are forcing the system to load them. It's likely that memory management for TCutG objects is not functioning as expected, resulting in inconsistent behavior when applying the cuts.

# Potential Solutions

1. Define a custom processor to handle histogram drawing.
2. Modify the way TCutG objects are loaded so they can be referenced directly within the artemis processor, rather than relying on the interpreter.

Currently, okawak is loading TCutG objects via the interpreter, but the exact memory management process for these objects remains unclear.
